import "primereact/resources/themes/lara-light-blue/theme.css"; // Tema
import "primereact/resources/primereact.min.css"; // PrimeReact ana stiller
import "primeicons/primeicons.css"; // PrimeIcons ikonlar
import "./globals.css";

import Header from "./components/layout/Header";
import WhatsappButton from "./components/layout/WhatsappButton";

export const metadata = {
  title: "Özhan Asker Malzemeleri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <Header />
        <WhatsappButton />
        <main className="min-h-screen z-0 container mx-auto py-12">
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
